[package]
name = "godot3-bunnymark"
version = "0.1.0"
authors = ["Carter Anderson <mcanders1@gmail.com>"]
edition = "2018"

[lib]
path = "benchmarks/lib.rs"
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.8"
euclid = "*"
rand = "0.6"
